name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      lesson:
        description: 'JSON of the lesson to be published'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Replace lesson
      run: |
        readonly lesson="${{ github.event.inputs.lesson }}"
        if [ ! -z "$lesson" ]; then
          echo "$lesson" > lesson.json
        fi

    - name: Build
      run: |
        npm install
        npm run-script build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
